#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
#


class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        counts = collections.Counter(s)
        countt = collections.Counter(t)
        if len(countt) != len(counts):
            for k, v in countt.items():
                if k not in s:
                    return k
        else:
            for k, v in countt.items():
                if v - counts[k] == 1:
                    return k
            
        
